apiVersion: v2
name: go-lock
description: A Helm chart for go-lock OAuth2/OpenID Connect service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - oauth2
  - openid-connect
  - authentication
  - authorization
home: https://github.com/freekieb7/go-lock
sources:
  - https://github.com/freekieb7/go-lock
maintainers:
  - name: freekieb7
    email: your-email@example.com
dependencies: []