apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-lock.fullname" . }}-secrets
  labels:
    {{- include "go-lock.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
  api-key: {{ .Values.secrets.apiKey | quote }}
  csrf-secret: {{ .Values.secrets.csrfSecret | quote }}
  session-secret: {{ .Values.secrets.sessionSecret | quote }}